export const PHONE_NUMBER = '9119723907'; // Replace with your specific phone number

export const CATEGORY_ITEMS = {
  Fertilizers: [
    { name: 'Nitrogen Fertilizer', price: 100 },
    { name: 'Phosphate Fertilizer', price: 120 },
    { name: 'Potash Fertilizer', price: 110 },
    { name: 'Calcium Fertilizer', price: 130 },
    { name: 'Magnesium Fertilizer', price: 140 },
    { name: 'Sulfur Fertilizer', price: 150 },
    { name: 'Micronutrient Fertilizer', price: 160 },
    { name: 'Organic Fertilizer', price: 170 },
    { name: 'Slow-Release Fertilizer', price: 180 },
    { name: 'Liquid Fertilizer', price: 190 },
  ],
  AnimalFeed: [
    { name: 'Cattle Feed', price: 80 },
    { name: 'Poultry Feed', price: 90 },
    { name: 'Swine Feed', price: 85 },
    { name: 'Sheep Feed', price: 95 },
    { name: 'Goat Feed', price: 100 },
    { name: 'Fish Feed', price: 110 },
    { name: 'Horse Feed', price: 120 },
    { name: 'Dog Feed', price: 130 },
    { name: 'Cat Feed', price: 140 },
    { name: 'Rabbit Feed', price: 150 },
  ],
  HumanFood: [
    { name: 'Rice', price: 50 },
    { name: 'Wheat', price: 60 },
    { name: 'Corn', price: 55 },
    { name: 'Barley', price: 65 },
    { name: 'Oats', price: 70 },
    { name: 'Rye', price: 75 },
    { name: 'Millet', price: 80 },
    { name: 'Sorghum', price: 85 },
    { name: 'Quinoa', price: 90 },
    { name: 'Buckwheat', price: 95 },
  ],
  Seeds: [
    { name: 'Tomato Seeds', price: 30 },
    { name: 'Cucumber Seeds', price: 40 },
    { name: 'Pepper Seeds', price: 35 },
    { name: 'Lettuce Seeds', price: 45 },
    { name: 'Carrot Seeds', price: 50 },
    { name: 'Radish Seeds', price: 55 },
    { name: 'Spinach Seeds', price: 60 },
    { name: 'Broccoli Seeds', price: 65 },
    { name: 'Cauliflower Seeds', price: 70 },
    { name: 'Pumpkin Seeds', price: 75 },
  ],
  MiscellaneousItems: [
    { name: 'Garden Tools', price: 150 },
    { name: 'Pesticides', price: 200 },
    { name: 'Herbicides', price: 180 },
    { name: 'Fungicides', price: 170 },
    { name: 'Irrigation Equipment', price: 160 },
    { name: 'Greenhouse Supplies', price: 190 },
    { name: 'Compost', price: 140 },
    { name: 'Mulch', price: 130 },
    { name: 'Plant Pots', price: 120 },
    { name: 'Soil Amendments', price: 110 },
  ],
};
