export const PHONE_NUMBER = '9119723907'; // Replace with your specific phone number

export const CATEGORY_ITEMS = {
  Fertilizers: [
    { name: 'Nitrogen Fertilizer', price: 100, imagePath: require('./assets/fertilizers/2.jpeg') },
    { name: 'Dr Earth Nitrogen Fetilizer', price: 120, imagePath: require('./assets/fertilizers/5.jpeg') },
    { name: 'SoilMost', price: 110, imagePath: require('./assets/fertilizers/6.jpeg') },
    { name: 'Veri Green', price: 130, imagePath: require('./assets/fertilizers/7.jpeg') },
    { name: 'Liquid-N', price: 140, imagePath: require('./assets/fertilizers/8.jpeg') },
    { name: 'PNF Neem Coated', price: 150, imagePath: require('./assets/fertilizers/9.jpeg') },
    { name: '46-0-0-0 Nutrien', price: 160, imagePath: require('./assets/fertilizers/10.jpeg') },
    { name: 'IFFCO Potassium Nitrate', price: 170, imagePath: require('./assets/fertilizers/11.jpeg') },
    { name: 'N-Balance', price: 180, imagePath: require('./assets/fertilizers/12.jpeg') },
    { name: 'Artal', price: 190, imagePath: require('./assets/fertilizers/13.jpeg') },
    { name: 'Liquiid Fertizer', price: 190, imagePath: require('./assets/fertilizers/14.jpeg') },
    { name: 'Eco Growth NK TE', price: 190, imagePath: require('./assets/fertilizers/20.jpeg') },
    { name: 'Uttam Neem Urea', price: 190, imagePath: require('./assets/fertilizers/21.jpeg') },
    { name: 'Potash Corp', price: 190, imagePath: require('./assets/fertilizers/23.jpeg') },
    { name: 'Sikko Urea', price: 190, imagePath: require('./assets/fertilizers/a1.jpeg') },
    { name: 'IFFCO Urea', price: 190, imagePath: require('./assets/fertilizers/a2.jpeg') },
    { name: 'Bharat Urea', price: 190, imagePath: require('./assets/fertilizers/a3.jpeg') },
    { name: 'Karbko Urea', price: 190, imagePath: require('./assets/fertilizers/a4.jpeg') },
    { name: 'PlantoGallery', price: 190, imagePath: require('./assets/fertilizers/a5.jpeg') },
    { name: 'Sardar', price: 190, imagePath: require('./assets/fertilizers/a6.jpeg') },   
  ],
  AnimalFeed: [
    { name: 'Family Farm', price: 80,imagePath: require('./assets/animal_feed/1.jpeg') },
    { name: 'Dailry Power', price: 80,imagePath: require('./assets/animal_feed/2.jpeg') },
    { name: 'Smiridhi', price: 80,imagePath: require('./assets/animal_feed/3.jpeg') },
    { name: 'GoMitra', price: 80,imagePath: require('./assets/animal_feed/4.jpeg') },   
    { name: 'Nutri Milk', price: 80,imagePath: require('./assets/animal_feed/5.jpeg') },
    { name: 'Godhanya Pellet', price: 80,imagePath: require('./assets/animal_feed/6.jpeg') },
    { name: 'Planta', price: 80,imagePath: require('./assets/animal_feed/7.jpeg') },
    { name: 'Sarso Khal', price: 80,imagePath: require('./assets/animal_feed/8.jpeg') },
    { name: 'Shaileza khal', price: 80,imagePath: require('./assets/animal_feed/9.jpeg') },
    { name: 'Panchsheel Sarso Khal', price: 80,imagePath: require('./assets/animal_feed/10.jpeg') },
    { name: 'Anuradha Sarso Khal', price: 80,imagePath: require('./assets/animal_feed/11.jpeg') },
    { name: 'Gopal Khal', price: 80,imagePath: require('./assets/animal_feed/12.jpeg') },
    { name: 'Dulhan Khal', price: 80,imagePath: require('./assets/animal_feed/13.jpeg') },
    { name: 'Gill Khal', price: 80,imagePath: require('./assets/animal_feed/14.jpeg') },  
    { name: 'Kamdhenu Sudh Chuni', price: 80,imagePath: require('./assets/animal_feed/15.jpeg') },  
  ],
  HumanFood: [
    { name: 'Khandsari', price: 50,imagePath: require('./assets/human_food/1.jpeg') },
    { name: 'Apple Vinegar', price: 50,imagePath: require('./assets/human_food/2.jpeg') },
    { name: 'Sugarcane Vinegar', price: 50,imagePath: require('./assets/human_food/4.jpeg') },
    { name: 'Jamun Vinegar', price: 50,imagePath: require('./assets/human_food/5.jpeg') },
    { name: 'Apple Vinegar', price: 50,imagePath: require('./assets/human_food/6.jpeg') },
    { name: 'Sugarcane Vinegar', price: 50,imagePath: require('./assets/human_food/7.jpeg') },    
  ],
  Seeds: [
    { name: 'Seeds', price: 30 ,imagePath: require('./assets/seeds/1.jpeg')},
    { name: 'Moongfali', price: 40 ,imagePath: require('./assets/seeds/2.jpeg')},
    { name: 'Wheat', price: 35 ,imagePath: require('./assets/seeds/3.jpeg')},
    { name: 'Baramasi', price: 45 ,imagePath: require('./assets/seeds/4.jpeg')},
    { name: 'Paddy Wheat 151', price: 50 ,imagePath: require('./assets/seeds/5.jpeg')},
    { name: 'Mahak-47', price: 55,imagePath: require('./assets/seeds/6.jpeg') },
    { name: 'Kisan Dhaniya Seed', price: 60 ,imagePath: require('./assets/seeds/7.jpeg')},
    { name: 'Maize Seed MG-4050', price: 65,imagePath: require('./assets/seeds/8.jpeg') },
    { name: 'Black Wheat Grain', price: 70 ,imagePath: require('./assets/seeds/9.jpeg')},
    { name: 'Watermelon Hybrid F1', price: 75 ,imagePath: require('./assets/seeds/10.jpeg')},
    { name: 'Hybrid Bajra', price: 30 ,imagePath: require('./assets/seeds/11.jpeg')},
    { name: 'Future Coriander Seed', price: 40 ,imagePath: require('./assets/seeds/12.jpeg')},
    { name: 'Rishika F1 Hybrid Okra', price: 35 ,imagePath: require('./assets/seeds/13.jpeg')},
    { name: 'CPM Seed', price: 45 ,imagePath: require('./assets/seeds/14.jpeg')},
    { name: 'Chirag Wheat', price: 50 ,imagePath: require('./assets/seeds/15.jpeg')},
    { name: 'Moong Seed', price: 50 ,imagePath: require('./assets/seeds/16.jpeg')},
    { name: 'Barsati Mooli', price: 55,imagePath: require('./assets/seeds/17.jpeg') },
    { name: 'Agro', price: 60 ,imagePath: require('./assets/seeds/18.jpeg')},
    { name: 'F1 Hybrid Chilli Seed', price: 65,imagePath: require('./assets/seeds/19.jpeg') },
    { name: 'Kanha F1 Hybrid Seed', price: 70 ,imagePath: require('./assets/seeds/20.jpeg')},
    { name: 'Radish Jaidev', price: 75 ,imagePath: require('./assets/seeds/21.jpeg')},
    { name: 'ShriRam Pradhan Tomato', price: 60 ,imagePath: require('./assets/seeds/22.jpeg')},
    { name: 'ShriRam 456 Cauliflower', price: 60 ,imagePath: require('./assets/seeds/23.jpeg')},
    { name: 'Farm Sona Rice Seed', price: 60 ,imagePath: require('./assets/seeds/24.jpeg')},
    { name: 'Shriram Nano', price: 60 ,imagePath: require('./assets/seeds/25.jpeg')},
    { name: 'Shri Ram Yamla', price: 60 ,imagePath: require('./assets/seeds/26.jpeg')},
    { name: 'N-53 Oninon', price: 60 ,imagePath: require('./assets/seeds/27.jpeg')},
    { name: 'Sweet Ruby Pea Seeds', price: 60 ,imagePath: require('./assets/seeds/28.jpeg')},
  ],
  MiscellaneousItems: [
    { name: 'Garden Tools', price: 150 ,imagePath: require('./assets/a.jpeg')},
    { name: 'Pesticides', price: 200 ,imagePath: require('./assets/a.jpeg')},
    { name: 'Herbicides', price: 180,imagePath: require('./assets/a.jpeg') },
    { name: 'Fungicides', price: 170,imagePath: require('./assets/a.jpeg') },
    { name: 'Irrigation Equipment', price: 160,imagePath: require('./assets/a.jpeg') },
    { name: 'Greenhouse Supplies', price: 190,imagePath: require('./assets/a.jpeg') },
    { name: 'Compost', price: 140 ,imagePath: require('./assets/a.jpeg')},
    { name: 'Mulch', price: 130 ,imagePath: require('./assets/a.jpeg')},
    { name: 'Plant Pots', price: 120 ,imagePath: require('./assets/a.jpeg')},
    { name: 'Soil Amendments', price: 110,imagePath: require('./assets/a.jpeg') },
  ],
};
